source('scripts/county_matching.R');source('scripts/reconcile_raw_county.R')
x<-data.frame(year=2004,state='AA',fips=c('01001','01001','','01003'),county=c('ONE','UNKNOWN','OUT OF STATE','THREE'),siteid=c('AA','AA','AA','COEX'))
r<-classify_removals(x)
stopifnot(identical(r,c('retained_candidate','county_UNKNOWN','county_OUT_OF_STATE','site_COEX_pre2023')))
y<-x[1,,drop=FALSE];z<-reconcile_counts(x[r=='retained_candidate',],y,c('year','state','fips'))
stopifnot(all(z$difference==0))
y<-rbind(y,y);z<-reconcile_counts(x[r=='retained_candidate',],y,c('year','state','fips'));stopifnot(sum(z$difference)==-1)
stopifnot(nrow(aggregate_keys(x[FALSE,],c('year','state'),'records'))==0)
cat('PASS exclusion hypotheses, exact aggregate comparison and unexplained difference detection\n')
