source('scripts/county_matching.R');source('scripts/audit_county_pilot.R')
d<-tempfile();dir.create(d);geo<-file.path(d,'geo');dir.create(geo)
write.csv(data.frame(fips=c('06001','06013'),state='CA',county=c('Alameda County','Contra Costa County'),start_year=2004,end_year=2019),file.path(geo,'counties.csv'),row.names=FALSE)
write.csv(data.frame(fips_a='06001',fips_b='06013'),file.path(geo,'edges.csv'),row.names=FALSE)
x<-data.frame(year=c(2004,2005,2020),state='CA',county='ALAMEDA',fips='06001',pathogen='SALMONELLA',travelint='NO',cxcidt='CX+')
clean<-file.path(d,'clean.csv');write.csv(x,clean,row.names=FALSE)
p<-expand.grid(year=2004:2019,cofip=c(1,13));p$stfip<-6;p$state<-'CA';p$county<-ifelse(p$cofip==1,'ALAMEDA','CONTRA COSTA');p$population<-10000
pop<-file.path(d,'pop.sas7bdat');haven::write_sas(p,pop)
before<-tools::md5sum(c(clean,pop))
out<-file.path(d,'ok','reports');audit_pilot(clean,pop,geo,out)
stopifnot(readLines(file.path(out,'status.txt'))[1]=='INPUT_AUDIT_PASS')
panel<-readRDS(file.path(dirname(out),'county_panel_INTERNAL.rds'))
stopifnot(nrow(panel)==32,sum(panel$count)==2,all(panel$population==10000),identical(before,tools::md5sum(c(clean,pop))))
x$fips[1]<-'';write.csv(x,clean,row.names=FALSE)
out<-file.path(d,'unresolved','reports');audit_pilot(clean,pop,geo,out)
stopifnot(readLines(file.path(out,'status.txt'))[1]=='REVIEW_REQUIRED',!file.exists(file.path(dirname(out),'county_panel_INTERNAL.rds')))
x$fips[1]<-'06001';write.csv(x,clean,row.names=FALSE)
p<-p[-1,];haven::write_sas(p,pop);out<-file.path(d,'missingpop','reports');audit_pilot(clean,pop,geo,out)
stopifnot(readLines(file.path(out,'status.txt'))[1]=='REVIEW_REQUIRED',!file.exists(file.path(dirname(out),'county_panel_INTERNAL.rds')))
unlink(d,recursive=TRUE);cat('PASS filtered cases, complete zero grid, population checks, unresolved-name gate, and immutable inputs\n')
