source('scripts/prepare_classification_monthly.R')
p<-data.frame(state='AA',fips='00001',year=2012,count=3)
x<-data.frame(state=rep('AA',3),fips='00001',year=2012,dtspec=as.Date(c('2012-01-02','2012-01-03',NA)),cxcidt=c('CX+','CIDT+','CIDT+'))
r<-classification_monthly_tables(x,p)
stopifnot(nrow(r$county)==12,r$county$classification_denominator[1]==2,r$county$cidt_classification_share[1]==.5,all(is.na(r$county$cidt_classification_share[-1])),r$annual$unassigned_records==1,sum(r$date_issues_by_category$unassigned)==1)
err<-function(z)inherits(try(z,silent=TRUE),'try-error')
bad<-x;bad$cxcidt[1]<-'PARASITIC';stopifnot(err(classification_monthly_tables(bad,p)))
bad<-x;bad$fips[1]<-'00002';stopifnot(err(classification_monthly_tables(bad,p)))
bad<-x;bad$dtspec[1]<-as.Date('2011-01-01');r<-classification_monthly_tables(bad,p);stopifnot(r$annual$unassigned_records==2)
bad<-p;bad$count<-4;stopifnot(err(classification_monthly_tables(x,bad)))
cat('CLASSIFICATION MONTHLY PREPARATION TEST PASS\n')
