stopifnot(requireNamespace('haven',quietly=TRUE))
d <- tempfile('county-fixture-');dir.create(d)
x <- data.frame(year=c(2023,2023,2023,2023),state=c('CA','CA','CT','CA'),county=c('Alpha','Alpha','Old County','Alpha'),fips=c('06001','','09001',''),pathogen=c('STEC','STEC','STEC','CYCLOSPORA'),siteid=c('CA','CA','CT','CA'))
p <- data.frame(year=c(2023,2023),state=c('CA','CT'),county=c('Alpha','Old County'),stfip=c(6,9),cofip=c(1,1),entryyear=c(1996,1996),population=c(100,NA))
haven::write_sas(x,file.path(d,'mmwr9625.sas7bdat'))
haven::write_sas(p,file.path(d,'cen9625.sas7bdat'))
haven::write_sas(p,file.path(d,'cen9625_para.sas7bdat'))
before <- tools::md5sum(list.files(d,full.names=TRUE))
out <- file.path(d,'reports')
status <- system2(file.path(R.home('bin'),'Rscript'),c('scripts/prepare_county_inputs.R',shQuote(d),shQuote(out)),stdout=TRUE,stderr=TRUE)
if(!is.null(attr(status,'status')))stop(paste(status,collapse='\n'))
r <- read.csv(file.path(out,'geographic_candidates_INTERNAL.csv'))
stopifnot(nrow(r)==4,all(!r$model_ready),all(r$records=='<5'))
stopifnot(identical(before,tools::md5sum(names(before))))
stopifnot(any(grepl('PREPARATION COMPLETE',readLines(file.path(out,'county_readiness.txt')))))
unlink(d,recursive=TRUE)
cat('PASS SAS-to-report integration, source checksums preserved, suppressed small counts and no model-ready rows\n')
