source('bin/input_validation.R');source('scripts/county_matching.R');source('scripts/audit_county_pilot.R')
x<-data.frame(year=2016:2019,state='CA',pathogen='CRYPTOSPORIDIUM')
p<-data.frame(year=2016:2019,state='CA',population=10000)
r<-prepare_analysis_inputs(x,p,p,'CRYPTOSPORIDIUM',parasite_end_year=2024)
stopifnot(identical(r$years,2016:2017),all(r$cases$year<=2017),all(r$census$year<=2017),sum(r$excluded$records)==2)
x$pathogen<-'CYCLOSPORA';r<-prepare_analysis_inputs(x,p,p,'CYCLOSPORA')
stopifnot(identical(r$years,2016:2019))
stopifnot(inherits(try(prepare_analysis_inputs(x,p,p,'CRYPTOSPORIDIUM',observation_years=2018:2019),silent=TRUE),'try-error'))
b<-tempfile();dir.create(b);geo<-file.path(b,'geo');dir.create(geo)
write.csv(data.frame(fips=c('06001','06013'),state='CA',county=c('Alameda','Contra Costa')),file.path(geo,'counties.csv'),row.names=FALSE)
write.csv(data.frame(fips_a='06001',fips_b='06013'),file.path(geo,'edges.csv'),row.names=FALSE)
x<-data.frame(year=2004:2019,state='CA',county='ALAMEDA',fips='06001',pathogen='CRYPTOSPORIDIUM',travelint='NO',cxcidt='PARASITIC')
clean<-file.path(b,'clean.csv');write.csv(x,clean,row.names=FALSE)
p<-expand.grid(year=2004:2019,cofip=c(1,13));p$state<-'CA';p$stfip<-6;p$county<-ifelse(p$cofip==1,'ALAMEDA','CONTRA COSTA');p$population<-10000
pop<-file.path(b,'pop.sas7bdat');haven::write_sas(p,pop)
audit_pilot(clean,pop,geo,file.path(b,'audit/reports'),'CRYPTOSPORIDIUM')
d<-readRDS(file.path(b,'audit/county_panel_INTERNAL.rds'));stopifnot(nrow(d)==28,sum(d$count)==14,max(d$year)==2017)
source('scripts/fit_county_pilot.R')
d$year[1]<-2018;saveRDS(d,file.path(b,'audit/county_panel_INTERNAL.rds'))
e<-try(validate_panel(file.path(b,'audit'),FALSE),silent=TRUE)
stopifnot(inherits(e,'try-error'),grepl('Stale Cryptosporidium',as.character(e)))
unlink(b,recursive=TRUE);cat('PASS state/county cutoff, Cyclospora unchanged, stale panel rejection\n')
