# Saved-fit regression only: supply a synthetic spline fixture generated by
# tests/test_monthly_spline_factorial.R. This test never fits a model.
source('scripts/run_monthly_spline_factorial.R')
fixture<-Sys.getenv('MONTHLY_RNG_TEST_FIXTURE')
if(!nzchar(fixture)||!file.exists(file.path(fixture,'fit.rds'))||!file.exists(file.path(fixture,'truth.csv')))stop('Set MONTHLY_RNG_TEST_FIXTURE to a saved synthetic spline fixture')
fitpath<-file.path(fixture,'fit.rds');truthpath<-file.path(fixture,'truth.csv')
fit<-readRDS(fitpath);spec<-attr(fit,'monthly_specification')
cutoff<-(spec$cutoff-11L)%/%12L;seasonal<-spec$seasonal
before<-tools::md5sum(c(fitpath,truthpath))
values<-function(ss)list(hyper=do.call(rbind,lapply(ss,function(s)s$hyperpar)),latent=do.call(cbind,lapply(ss,function(s)s$latent[,1])))
batch<-function(ambient,protocol){set.seed(ambient);values(monthly_posterior_batch(100L,fit,1:4,'APredictor',640000000L,1L,protocol))}
a<-batch(100,'explicit_config_v2');b<-batch(101,'explicit_config_v2')
stopifnot(identical(a,b))
# The legacy path must retain the original semantics exactly.
set.seed(100)
legacy_direct<-values(INLA::inla.posterior.sample(100L,fit,selection=list(APredictor=1:4),seed=640000001L,num.threads='1:1',skew.corr=FALSE))
stopifnot(identical(legacy_direct,batch(100,'legacy_v1')))
stopifnot(!identical(batch(100,'legacy_v1'),batch(101,'legacy_v1')))
stopifnot(inherits(try(monthly_posterior_batch(1L,fit,1L,'APredictor',640000000L,1L,'unknown'),silent=TRUE),'try-error'))
# Full scoring, predictive RNG, exposure and metadata reproducibility.
work<-tempfile('monthly-rng-protocol-',tmpdir='/tmp');dir.create(work)
for(i in 1:2){
 set.seed(321+i)
 audit_monthly_saved(fitpath,truthpath,cutoff,seasonal,file.path(work,paste0('v2_',i)),640000000L,draws=100L,adapter=validate_saved_monthly_spline,rng_protocol='explicit_config_v2')
}
for(name in c('stream_scores.csv','aggregate_tails.csv','shape_streams.csv','pooled_cell_scores.csv','rng_protocol.csv'))stopifnot(identical(readLines(file.path(work,'v2_1',name)),readLines(file.path(work,'v2_2',name))))
stopifnot(identical(readRDS(file.path(work,'v2_1/aggregate_draws_INTERNAL.rds')),readRDS(file.path(work,'v2_2/aggregate_draws_INTERNAL.rds'))))
meta<-read.csv(file.path(work,'v2_1/rng_protocol.csv'))
stopifnot(nrow(meta)==1,identical(as.character(meta$protocol),'explicit_config_v2'),meta$base_seed==640000000,meta$stream_stride==50000,meta$batch_size==100,meta$inla_seed_offset==0,meta$r_configuration_seed_offset==20000,meta$predictive_seed_offset==10000)
stopifnot(all(c('r_rng_kind','r_version','inla_version')%in%names(meta)),meta$r_rng_kind==paste(RNGkind(),collapse=' / '),meta$r_version==as.character(getRversion()),meta$inla_version==as.character(packageVersion('INLA')))
stopifnot(identical(before,tools::md5sum(c(fitpath,truthpath))))
cat('Explicit v2 reproducibility, legacy preservation, full scoring and metadata PASS:',work,'\n')
